name: CI

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install Tailscale
      run: |
        curl -fsSL https://tailscale.com/install.sh | sh
        sudo tailscale up --authkey=${{ secrets.TAILSCALE_AUTHKEY }} --hostname=gh-runner-${{ github.run_id }} --accept-routes=true --advertise-routes=10.0.0.0/8,172.16.0.0/12,192.168.0.0/16
        sudo systemctl enable --now tailscaled

    - name: Get Tailscale IP
      id: get-ip
      run: |
        tailscale_status=$(tailscale status --json)
        tailscale_ip=$(echo "$tailscale_status" | jq -r '.Self.TailscaleIPs[0]')
        echo "Tailscale IP: $tailscale_ip"
        echo "::set-output name=tailscale_ip::$tailscale_ip"

    - name: Install xRDP, XFCE, and dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y xrdp xorgxrdp xfce4 xfce4-goodies  # Install xRDP, Xorg backend, and XFCE
        # Check if the user 'runneradmin' exists before attempting to create it.
        if ! id "runneradmin" &>/dev/null; then
          sudo adduser runneradmin
          echo 'runneradmin:P@ssw0rd!' | sudo chpasswd
          sudo usermod -aG sudo,adm runneradmin
        else
          echo "User 'runneradmin' already exists.  Setting password and groups."
          echo 'runneradmin:P@ssw0rd!' | sudo chpasswd  # Still set the password
          sudo usermod -aG sudo,adm runneradmin # And ensure group membership
        fi
        sudo sed -i 's/^allowed_users=console/allowed_users=anybody/' /etc/X11/Xwrapper.config
        # Check for existing .xsession file before creating/overwriting
        if [ ! -f /home/runneradmin/.xsession ]; then
            echo "xfce4-session" | sudo tee /home/runneradmin/.xsession # Set XFCE
            sudo chown runneradmin:runneradmin /home/runneradmin/.xsession
            sudo chmod +x /home/runneradmin/.xsession
        else
            echo "File /home/runneradmin/.xsession already exists. Skipping creation."
        fi


    - name: Configure xRDP
      run: |
        sudo sed -i 's/port=3389/port=3389/g' /etc/xrdp/xrdp.ini
        sudo systemctl restart xrdp
        sudo systemctl enable xrdp

    - name: Improve RDP performance
      run: |
        # Reduce color depth
        sudo sed -i 's/MaxBPP=32/MaxBPP=16/g' /etc/xrdp/xrdp.ini
        sudo sed -i 's/ColorDepth=32/ColorDepth=16/g' /etc/xrdp/xrdp.ini
        # Disable sound redirection (if not needed)
        sudo sed -i 's/EnableSound=true/EnableSound=false/g' /etc/xrdp/xrdp.ini
         # Disable clipboard redirection(If not needed)
        sudo sed -i 's/EnableClipboard=true/EnableClipboard=false/g' /etc/xrdp/xrdp.ini
        sudo systemctl restart xrdp

    - name: Keep Workflow Alive
      run: |
        echo "RDP to: ${{ steps.get-ip.outputs.tailscale_ip }}:3389"
        echo "Username: runneradmin"
        echo "Password: P@ssw0rd!"
        echo "Workflow running indefinitely.  Manually cancel the workflow to stop."
        while true; do
          sleep 3600
          echo "Still running..."
        done
