name: Persistent Tailscale Connection

on: [workflow_dispatch]

jobs:
  setup_and_maintain:
    runs-on: self-hosted  # Use a self-hosted runner for 24/7 operation
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Install Tailscale
      shell: bash
      run: |
        curl -fsSL https://tailscale.com/install.sh | sh
        if [ $? -ne 0 ]; then
          echo "Tailscale installation failed."
          exit 1
        fi

    - name: Authenticate Tailscale
      shell: bash
      run: |
        sudo tailscale up --authkey=${{ secrets.TAILSCALE_AUTHKEY }} --hostname=gha-runner-${{ github.run_id }} --accept-routes=false --accept-dns=false
      env:
        TAILSCALE_AUTHKEY: ${{ secrets.TAILSCALE_AUTHKEY }}

    - name: Display Connection Info
      shell: bash
      run: |
        tailscaleIP=$(tailscale ip -4)
        echo "=== Tailscale Connection Information ==="
        echo "IP Address: $tailscaleIP"
        echo "Username: ubuntu" # Default username for Ubuntu runners
        echo "Password: <Use RDP client to enter password>" # Password is set as a secret
        echo "`nTo connect via Remote Desktop Connection (or compatible RDP client):"
        echo "  1. Open your Remote Desktop Connection tool."
        echo "  2. Enter the IP Address shown above."
        echo "  3. When prompted, use username 'ubuntu' and the password you set in the RDP_PASSWORD secret."
        echo "`nUse 'tailscale status' to verify connection:"
        tailscale status

    - name: Install and Configure xRDP (Optional - for GUI access)
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y xrdp
        sudo systemctl enable xrdp --now

        # Debugging & Fix Attempts for chpasswd Error:
        echo "Attempting to set password for ubuntu user..."

        # 1. Verify sudo is working (basic command)
        sudo whoami
        if [ $? -ne 0 ]; then
          echo "Error: sudo command failed. Permissions issue?"
          exit 1
        fi
        echo "sudo command successful."

        # 2. Try chpasswd with NO options (plain text password)
        echo "ubuntu:${{ secrets.RDP_PASSWORD }}" | sudo chpasswd
        if [ $? -eq 0 ]; then
          echo "Password changed successfully (plain text)."
        else
          echo "Password change failed (plain text). Trying -e (encrypted)..."

          # 3. Try chpasswd with -e (encrypted password) - REQUIRES SEPARATE ENCRYPTION STEP
          # First, create an encrypted password using openssl:
          encrypted_password=$(openssl passwd -crypt "${{ secrets.RDP_PASSWORD }}")
          if [ $? -ne 0 ]; then
            echo "Error: openssl password encryption failed."
            exit 1
          fi
          echo "Encrypted password generated."
          echo "ubuntu:$encrypted_password" | sudo chpasswd -e # Use -e for encrypted input

          if [ $? -eq 0 ]; then
            echo "Password changed successfully (encrypted)."
          else
            echo "Password change failed (encrypted).  Investigate PAM or permissions."
            cat /var/log/auth.log # Check auth logs for clues if available
            exit 1 # Exit if all attempts fail
          fi
        fi

        sudo sed -i 's/allowed_users=console/allowed_users=anybody/' /etc/X11/Xwrapper.config
        sudo sed -i 's/#xfce_session/xfce_session/' /etc/xrdp/startwm.sh

    - name: Maintain Tailscale Connection
      shell: bash
      run: |
        echo "Maintaining Tailscale connection indefinitely..."
        while true; do
            tailscaleStatus=$(tailscale status 2>&1)
            if [[ $tailscaleStatus != *"logged in"* ]]; then
                echo "Tailscale connection lost or not logged in. Attempting to reconnect..."
                sudo tailscale up --authkey=${{ secrets.TAILSCALE_AUTHKEY }} --hostname=gha-runner-${{ github.run_id }} --accept-routes=false --accept-dns=false
            fi
            sleep 300  # Check connection every 5 minutes
        done

    - name: Disconnect Tailscale (Cleanup)
      if: always() # Always disconnect, regardless of trigger
      shell: bash
      run: sudo tailscale down
