name: CI

on: [push, workflow_dispatch]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Install Tailscale
      shell: bash
      run: |
        curl -fsSL https://tailscale.com/install.sh | sh
        if [ $? -ne 0 ]; then
          echo "Tailscale installation failed."
          exit 1
        fi

    - name: Authenticate Tailscale
      shell: bash
      run: |
        sudo tailscale up --authkey=${{ secrets.TAILSCALE_AUTHKEY }} --hostname=gha-runner-${{ github.run_id }} --accept-routes=false --accept-dns=false
      env:
        TAILSCALE_AUTHKEY: ${{ secrets.TAILSCALE_AUTHKEY }}

    - name: Display Connection Info
      shell: bash
      run: |
        tailscaleIP=$(tailscale ip -4)
        echo "=== Tailscale Connection Information ==="
        echo "IP Address: $tailscaleIP"
        echo "Use 'tailscale status' to verify connection:"
        tailscale status

    - name: Install and Configure xRDP (Optional - for GUI access)
      if: ${{ github.event_name == 'workflow_dispatch' }}  # Only on manual trigger
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y xrdp
        sudo systemctl enable xrdp --now
        echo "ubuntu:${{ secrets.RDP_PASSWORD }}" | sudo chpasswd
        sudo sed -i 's/allowed_users=console/allowed_users=anybody/' /etc/X11/Xwrapper.config
        sudo sed -i 's/#xfce_session/xfce_session/' /etc/xrdp/startwm.sh

  maintain_xrdp:
    needs: setup
    runs-on: ubuntu-latest
    timeout-minutes: 65
    steps:
      - name: Reinstall Tailscale and Maintain Connection (for xRDP)
        if: ${{ github.event_name == 'workflow_dispatch' }}
        shell: bash
        run: |
          # Reinstall Tailscale (for maintenance)
          curl -fsSL https://tailscale.com/install.sh | sh
          if [ $? -ne 0 ]; then
            echo "Tailscale reinstallation failed."
            exit 1
          fi

          # Maintain Tailscale Connection
          echo "Maintaining Tailscale connection for xRDP for up to 60 minutes..."
          startTime=$(date +%s)
          while true; do
              currentTime=$(date +%s)
              elapsedTime=$((currentTime - startTime))

              if [[ $elapsedTime -ge 3600 ]]; then  # 60 minutes
                  echo "60-minute timeout reached. Exiting."
                  break
              fi

              tailscaleStatus=$(tailscale status 2>&1)
              if [[ $tailscaleStatus != *"logged in"* ]]; then
                  echo "Tailscale connection lost or not logged in. Attempting to reconnect..."
                  sudo tailscale up --authkey=${{ secrets.TAILSCALE_AUTHKEY }} --hostname=gha-runner-${{ github.run_id }} --accept-routes=false --accept-dns=false
              fi
              sleep 30
          done

      - name: Disconnect Tailscale (Cleanup)
        if: always()
        shell: bash
        run: sudo tailscale down
