name: CI

on: [push, workflow_dispatch]

jobs:
  setup_and_maintain:  # Combined job
    runs-on: ubuntu-latest
    timeout-minutes: 245  # Timeout applies to the entire job, set to slightly over 4 hours
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Install Tailscale
      shell: bash
      run: |
        curl -fsSL https://tailscale.com/install.sh | sh
        if [ $? -ne 0 ]; then
          echo "Tailscale installation failed."
          exit 1
        fi

    - name: Authenticate Tailscale
      shell: bash
      run: |
        sudo tailscale up --authkey=${{ secrets.TAILSCALE_AUTHKEY }} --hostname=gha-runner-${{ github.run_id }} --accept-routes=false --accept-dns=false
      env:
        TAILSCALE_AUTHKEY: ${{ secrets.TAILSCALE_AUTHKEY }}

    - name: Display Connection Info
      shell: bash
      run: |
        tailscaleIP=$(tailscale ip -4)
        echo "=== Tailscale Connection Information ==="
        echo "IP Address: $tailscaleIP"
        echo "Username: ubuntu" # Default username for Ubuntu runners
        echo "Password: <Use RDP client to enter password>" # Password is set as a secret
        echo "`nTo connect via Remote Desktop Connection (or compatible RDP client):"
        echo "  1. Open your Remote Desktop Connection tool."
        echo "  2. Enter the IP Address shown above."
        echo "  3. When prompted, use username 'ubuntu' and the password you set in the RDP_PASSWORD secret."
        echo "`nUse 'tailscale status' to verify connection:"
        tailscale status

    - name: Install and Configure xRDP (Optional - for GUI access)
      if: ${{ github.event_name == 'workflow_dispatch' }}  # Only on manual trigger
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y xrdp
        sudo systemctl enable xrdp --now
        echo "ubuntu:${{ secrets.RDP_PASSWORD }}" | sudo chpasswd
        sudo sed -i 's/allowed_users=console/allowed_users=anybody/' /etc/X11/Xwrapper.config
        sudo sed -i 's/#xfce_session/xfce_session/' /etc/xrdp/startwm.sh

    - name: Reinstall Tailscale and Maintain Connection (for xRDP)
      if: ${{ github.event_name == 'workflow_dispatch' }}  # Only on manual trigger
      shell: bash
      run: |
        # Reinstall Tailscale (for maintenance)
        curl -fsSL https://tailscale.com/install.sh | sh
        if [ $? -ne 0 ]; then
          echo "Tailscale reinstallation failed."
          exit 1
        fi

        # Maintain Tailscale Connection for 4 Hours
        echo "Maintaining Tailscale connection for xRDP for up to 4 hours..."
        startTime=$(date +%s)
        while true; do
            currentTime=$(date +%s)
            elapsedTime=$((currentTime - startTime))

            if [[ $elapsedTime -ge 14400 ]]; then  # 4 hours = 14400 seconds
                echo "4-hour timeout reached. Exiting."
                break
            fi

            tailscaleStatus=$(tailscale status 2>&1)
            if [[ $tailscaleStatus != *"logged in"* ]]; then
                echo "Tailscale connection lost or not logged in. Attempting to reconnect..."
                sudo tailscale up --authkey=${{ secrets.TAILSCALE_AUTHKEY }} --hostname=gha-runner-${{ github.run_id }} --accept-routes=false --accept-dns=false
            fi
            sleep 30
        done

    - name: Disconnect Tailscale (Cleanup)
      if: always() # Always disconnect, regardless of trigger
      shell: bash
      run: sudo tailscale down
