name: CI

on: [push, workflow_dispatch]

jobs:
  setup_and_maintain:
    runs-on: ubuntu-latest
    timeout-minutes: 245
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Install Tailscale
      shell: bash
      run: |
        curl -fsSL https://tailscale.com/install.sh | sh
        if [ $? -ne 0 ]; then
          echo "Tailscale installation failed."
          exit 1
        fi

    - name: Authenticate Tailscale
      shell: bash
      run: |
        sudo tailscale up --authkey=${{ secrets.TAILSCALE_AUTHKEY }} --hostname=gha-runner-${{ github.run_id }} --accept-routes=false --accept-dns=false
      env:
        TAILSCALE_AUTHKEY: ${{ secrets.TAILSCALE_AUTHKEY }}

    - name: Display Connection Info
      shell: bash
      run: |
        tailscaleIP=$(tailscale ip -4)
        echo "=== Tailscale Connection Information ==="
        echo "IP Address: $tailscaleIP"
        echo "Username: ubuntu" # Default username for Ubuntu runners
        echo "Password: <Use RDP client to enter password>" # Password is set as a secret
        echo "`nTo connect via Remote Desktop Connection (or compatible RDP client):"
        echo "  1. Open your Remote Desktop Connection tool."
        echo "  2. Enter the IP Address shown above."
        echo "  3. When prompted, use username 'ubuntu' and the password you set in the RDP_PASSWORD secret."
        echo "`nUse 'tailscale status' to verify connection:"
        tailscale status

    - name: Install and Configure xRDP (Optional - for GUI access)
      if: ${{ github.event_name == 'workflow_dispatch' }}
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y xrdp
        sudo systemctl enable xrdp --now

        # Debugging & Fix Attempts for chpasswd Error:
        echo "Attempting to set password for ubuntu user..."

        # 1. Verify sudo is working (basic command)
        sudo whoami
        if [ $? -ne 0 ]; then
          echo "Error: sudo command failed. Permissions issue?"
          exit 1
        fi
        echo "sudo command successful."

        # 2. Try forcing password change with --force
        echo "ubuntu:${{ secrets.RDP_PASSWORD }}" | sudo chpasswd --force
        if [ $? -eq 0 ]; then
          echo "Password changed successfully (with --force)."
        else
          echo "Password change failed (with --force), trying -f (short flag)."
          # 3. Try forcing with short flag -f
          echo "ubuntu:${{ secrets.RDP_PASSWORD }}" | sudo chpasswd -f
          if [ $? -eq 0 ]; then
            echo "Password changed successfully (with -f)."
          else
            echo "Password change failed (with -f). Trying without force..."
             # 4. Try without force again (just in case)
            echo "ubuntu:${{ secrets.RDP_PASSWORD }}" | sudo chpasswd
            if [ $? -eq 0 ]; then
              echo "Password changed successfully (without force - weird)."
            else
              echo "Password change failed AGAIN (without force).  Investigate PAM or permissions."
              cat /var/log/auth.log # Check auth logs for clues if available
              exit 1 # Exit if all attempts fail
            fi
          fi
        fi


        sudo sed -i 's/allowed_users=console/allowed_users=anybody/' /etc/X11/Xwrapper.config
        sudo sed -i 's/#xfce_session/xfce_session/' /etc/xrdp/startwm.sh

    - name: Reinstall Tailscale and Maintain Connection (for xRDP)
      if: ${{ github.event_name == 'workflow_dispatch' }}
      shell: bash
      run: |
        # Reinstall Tailscale (for maintenance)
        curl -fsSL https://tailscale.com/install.sh | sh
        if [ $? -ne 0 ]; then
          echo "Tailscale reinstallation failed."
          exit 1
        fi

        # Maintain Tailscale Connection for 4 Hours
        echo "Maintaining Tailscale connection for xRDP for up to 4 hours..."
        startTime=$(date +%s)
        while true; do
            currentTime=$(date +%s)
            elapsedTime=$((currentTime - startTime))

            if [[ $elapsedTime -ge 14400 ]]; then  # 4 hours = 14400 seconds
                echo "4-hour timeout reached. Exiting."
                break
            fi

            tailscaleStatus=$(tailscale status 2>&1)
            if [[ $tailscaleStatus != *"logged in"* ]]; then
                echo "Tailscale connection lost or not logged in. Attempting to reconnect..."
                sudo tailscale up --authkey=${{ secrets.TAILSCALE_AUTHKEY }} --hostname=gha-runner-${{ github.run_id }} --accept-routes=false --accept-dns=false
            fi
            sleep 30
        done

    - name: Disconnect Tailscale (Cleanup)
      if: always() # Always disconnect, regardless of trigger
      shell: bash
      run: sudo tailscale down
